old oxid 7 phpunit

diff --git a/.github/workflows/development.yml b/.github/workflows/development.yml
--- a/.github/workflows/development.yml
+++ b/.github/workflows/development.yml
@@ -149,34 +149,37 @@ jobs:
         run: |
           docker compose exec -T php mv /var/www/source/extensions/easycredit/.github/test_config_oxid7.yml /var/www/test_config.yml
           
-      - name: Run phpunit tests for v3 API
-        run: |
-          docker compose exec -T \
-           php /var/www/vendor/bin/phpunit \
-             -c /var/www/source/extensions/easycredit/tests/phpunit.xml \
-             --testsuite=Integration \
-             --bootstrap=/var/www/vendor/oxid-esales/testing-library/bootstrap.php \
-             /var/www/source/extensions/easycredit/tests | tee integration_PHP${{ matrix.php-versions }}_phpunit_log.txt 2>&1 || true
-          if grep -q -Ei 'fail|\\.\\=\\=|Warning|Notice|Deprecated|Fatal|Error' integration_PHP${{ matrix.php-versions }}_phpunit_log.txt; then 
-            exit 1; 
-          fi          
+      # - name: Run phpunit tests for v3 API
+      #  run: |
+      #    docker compose exec -T \
+      #     php /var/www/vendor/bin/phpunit \
+      #       -c /var/www/source/extensions/easycredit/tests/phpunit.xml \
+      #       --testsuite=Integration \
+      #       --bootstrap=/var/www/vendor/oxid-esales/testing-library/bootstrap.php \
+      #       /var/www/source/extensions/easycredit/tests | tee integration_PHP${{ matrix.php-versions }}_phpunit_log.txt 2>&1 || true
+      #    if grep -q -Ei 'fail|\\.\\=\\=|Warning|Notice|Deprecated|Fatal|Error' integration_PHP${{ matrix.php-versions }}_phpunit_log.txt; then 
+      #      exit 1; 
+      #    fi          
 
-      - name: Configure module for v2 API
-        run: |
-          mkdir -p source/var/www/var/configuration/shops/1/modules
-          echo "${{ secrets.MODULE_SETTINGS_OXID7_V2 }}" > source/var/configuration/shops/1/modules/osceasycredit.yaml
+      # - name: Configure module for v2 API
+      #  run: |
+      #    mkdir -p source/var/www/var/configuration/shops/1/modules
+      #    echo "${{ secrets.MODULE_SETTINGS_OXID7_V2 }}" > source/var/configuration/shops/1/modules/osceasycredit.yaml
 
-      - name: Run phpunit tests for v2 API
+      # - name: Run phpunit tests for v2 API
+      #  run: |
+      #    docker compose exec -T \
+      #     php /var/www/vendor/bin/phpunit \
+      #       -c /var/www/source/extensions/easycredit/tests/phpunit.xml \
+      #       --testsuite=Integration \
+      #       --bootstrap=/var/www/vendor/oxid-esales/testing-library/bootstrap.php \
+      #       /var/www/source/extensions/easycredit/tests | tee integration_PHP${{ matrix.php-versions }}_phpunit_log.txt 2>&1 || true
+      #    if grep -q -Ei 'fail|\\.\\=\\=|Warning|Notice|Deprecated|Fatal|Error' integration_PHP${{ matrix.php-versions }}_phpunit_log.txt; then 
+      #      exit 1; 
+      #    fi    
+      - name: Run tests with testing lib against v3 API
         run: |
-          docker compose exec -T \
-           php /var/www/vendor/bin/phpunit \
-             -c /var/www/source/extensions/easycredit/tests/phpunit.xml \
-             --testsuite=Integration \
-             --bootstrap=/var/www/vendor/oxid-esales/testing-library/bootstrap.php \
-             /var/www/source/extensions/easycredit/tests | tee integration_PHP${{ matrix.php-versions }}_phpunit_log.txt 2>&1 || true
-          if grep -q -Ei 'fail|\\.\\=\\=|Warning|Notice|Deprecated|Fatal|Error' integration_PHP${{ matrix.php-versions }}_phpunit_log.txt; then 
-            exit 1; 
-          fi     
+          docker compose exec -T php /var/www/vendor/bin/runtests   
 
   run-b6-matrix:
     if: startsWith(github.ref_name, 'b-6.')
